# Use native CPU
# Current triple can be printed with: rustc -vV

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-Ctarget-cpu=native"]
